=== Soreepeong/FFXIV-ExcelMerge/ExcelMerge/Presets/exceltransformconfig.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://xivalexander/exceltransformconfig.schema.json",
  "title": "Excel String Transformation Configuration",
  "description": "Describe how to transform cells",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "revision": {
      "type": "integer",
      "default": 1,
      "minimum": 1
    },
    "description": {
      "type": "string"
    },
    "targetLanguage": {
      "type": "string",
      "enum": [
        "Japanese",
        "English",
        "German",
        "French",
        "ChineseSimplified",
        "ChineseTraditional",
        "Korean"
      ]
    },
    "sourceLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Japanese",
          "English",
          "German",
          "French",
          "ChineseSimplified",
          "ChineseTraditional",
          "Korean"
        ]
      },
      "minItems": 1,
      "maxItems": 7
    },
    "columnMap": {
      "type": "object",
      "patternProperties": {
        "^(?!#)": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "pluralMap": {
      "type": "object",
      "patternProperties": {
        "^(?!#)": {
          "type": "array",
          "items": {
            "type": [
              "integer",
              "null"
            ],
            "minItems": 2,
            "maxItems": 4
          }
        }
      }
    },
    "targetGroups": {
      "type": "object",
      "patternProperties": {
        "[^#][A-Za-z0-9]+": {
          "type": [
            "array",
            "integer"
          ],
          "items": {
            "type": [
              "integer"
            ],
            "minItems": 1
          }
        }
      }
    },
    "sourceReplacements": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        }
      }
    },
    "replacementTemplates": {
      "type": "object",
      "patternProperties": {
        "[^#][A-Za-z0-9]+": {
          "type": "object",
          "properties": {
            "from": {
              "type": "string"
            },
            "to": {
              "type": "string"
            }
          }
        }
      }
    },
    "ignoredCells": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          },
          "column": {
            "type": "integer"
          },
          "forceLanguage": {
            "type": ["string", "null"],
            "enum": [
              "Japanese",
              "English",
              "German",
              "French",
              "ChineseSimplified",
              "ChineseTraditional",
              "Korean"
            ]
          },
          "forceString": {
            "type": ["string", "null"]
          }
        },
        "required": [
          "name",
          "id",
          "column"
        ]
      }
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "targetGroups": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "replaceTo": {
            "type": "string"
          },
          "stringPattern": {
            "type": "string"
          }
        },
        "required": [
          "targetGroups",
          "replaceTo"
        ]
      }
    }
  },
  "required": [
    "name",
    "targetLanguage",
    "sourceLanguages",
    "targetGroups",
    "rules"
  ]
}

=== Soreepeong/FFXIV-ExcelMerge/ExcelMerge/Presets/CrossRegionRemapping.json
{
  "name": "Maps column across regions.",
  "description": "",
  "targetLanguage": "English",
  "sourceLanguages": [
    "English",
    "Japanese"
  ],
  "columnMap": {
    "^DawnMemberUiParam$": {
      "Japanese": [1],
      "English": [1],
      "German": [1],
      "French": [1],
      "ChineseSimplified": [2],
      "Korean": [2]
    },
    "^DescriptionStandaloneTransient": {
      "Japanese": [1, 2],
      "English": [1, 2],
      "German": [1, 2],
      "French": [1, 2],
      "ChineseSimplified": [0, 1],
      "Korean": [0, 1]
    },
    "^NpcYell$": {
      "Japanese": [10],
      "English": [10],
      "German": [10],
      "French": [10],
      "ChineseSimplified": [9],
      "Korean": [9]
    },
    "^MainCommand": {
      "Japanese": [5, 6],
      "English": [5, 6],
      "German": [5, 6],
      "French": [5, 6],
      "ChineseSimplified": [4, 5],
      "Korean": [4, 5]
    },
    "^Ornament": {
      "Japanese": [9, 11],
      "English": [9, 11],
      "German": [9, 11],
      "French": [9, 11],
      "ChineseSimplified": [7, 9],
      "Korean": [7, 9]
    }
  },
  "pluralMap": {
    "# comment 1": [
      "singularColumnIndex",
      "pluralColumnIndex",
      "optionalCapitalizedColumnIndex",
      "languageSpecificColumnIndex"
    ],
    "# comment 2": "Priority if the language does not have plural forms: optionalCapitalized, singular, plural",
    "^BNpcName$": [0, 2],
    "^BuddyEquip$": [0, 2, 8],
    "^DeepDungeonEquipment$": [1, 3, 9],
    "^DeepDungeonItem$": [1, 3, 9],
    "^DeepDungeonMagicStone$": [1, 3, 9],
    "^ENpcResident$": [0, 2],
    "^EObjName$": [0, 2],
    "^EventItem$": [0, 2, 9],
    "^GatheringPointName$": [0, 2],
    "^GCRank(Gridania|Limsa|Uldah)(Male|Female)Text$": [0, 2],
    "^Item$": [0, 2, 9],
    "^Mount$": [0, 2],
    "^Ornament$": [9, 11],
    "^PlaceName$": [0, 2, null, 8],
    "^Treasure$": [0, 2],
    "^Tribe$": [0, 1]
  },
  "targetGroups": {},
  "rules": []
}

=== Soreepeong/FFXIV-ExcelMerge/ExcelMerge/Presets/Korean_SayQuestEnglish.json
{
  "name": "Set say quest to require English input instead",
  "description": "",
  "targetLanguage": "Korean",
  "sourceLanguages": [
    "Korean",
    "English"
  ],
  "targetGroups": {},
  "replacementTemplates": {},
  "ignoredCells": [
    {"name": "quest/002/FesNyr102_00287", "id": 96, "column": 1, "forceLanguage": "English"},
    {"name": "quest/004/SubSea075_00487", "id": 54, "column": 1, "forceLanguage": "English"},
    {"name": "quest/004/SubSea075_00487", "id": 63, "column": 1, "forceLanguage": "English"},
    {"name": "quest/005/ChrHdb505_00502", "id": 58, "column": 1, "forceLanguage": "English"},
    {"name": "quest/014/BanIxa104_01497", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/014/GaiUse314_01455", "id": 109, "column": 1, "forceLanguage": "English"},
    {"name": "quest/014/SubFst122_01428", "id": 54, "column": 1, "forceLanguage": "English"},
    {"name": "quest/014/SubFst122_01428", "id": 62, "column": 1, "forceLanguage": "English"},
    {"name": "quest/014/SubWil101_01429", "id": 54, "column": 1, "forceLanguage": "English"},
    {"name": "quest/014/SubWil101_01429", "id": 62, "column": 1, "forceLanguage": "English"},
    {"name": "quest/015/BanIxa204_01507", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/015/BanIxa302_01515", "id": 59, "column": 1, "forceLanguage": "English"},
    {"name": "quest/015/BanIxa404_01501", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/015/BanIxa607_01568", "id": 58, "column": 1, "forceLanguage": "English"},
    {"name": "quest/016/HeaVna607_01656", "id": 59, "column": 1, "forceLanguage": "English"},
    {"name": "quest/016/JobSch560_01674", "id": 65, "column": 1, "forceLanguage": "English"},
    {"name": "quest/019/HeaVnz706_01910", "id": 68, "column": 1, "forceLanguage": "English"},
    {"name": "quest/019/HeaVnz905_01970", "id": 88, "column": 1, "forceLanguage": "English"},
    {"name": "quest/019/HeaVnz905_01970", "id": 89, "column": 1, "forceLanguage": "English"},
    {"name": "quest/020/JobDrk500_02058", "id": 55, "column": 1, "forceLanguage": "English"},
    {"name": "quest/022/BanGna003_02257", "id": 108, "column": 1, "forceLanguage": "English"},
    {"name": "quest/022/BanGna602_02277", "id": 54, "column": 1, "forceLanguage": "English"},
    {"name": "quest/022/BanMog202_02295", "id": 61, "column": 1, "forceLanguage": "English"},
    {"name": "quest/022/ChrEnd204_02210", "id": 64, "column": 1, "forceLanguage": "English"},
    {"name": "quest/025/JobPld680_02574", "id": 120, "column": 1, "forceLanguage": "English"},
    {"name": "quest/025/StmBda401_02500", "id": 96, "column": 1, "forceLanguage": "English"},
    {"name": "quest/026/StmBdz217_02689", "id": 85, "column": 1, "forceLanguage": "English"},
    {"name": "quest/026/StmBdz223_02695", "id": 55, "column": 1, "forceLanguage": "English"},
    {"name": "quest/027/StmBdz506_02757", "id": 54, "column": 1, "forceLanguage": "English"},
    {"name": "quest/028/StmBdz908_02864", "id": 60, "column": 1, "forceLanguage": "English"},
    {"name": "quest/029/BanKjn401_02985", "id": 50, "column": 1, "forceLanguage": "English"},
    {"name": "quest/030/FesHlw402_03012", "id": 66, "column": 1, "forceLanguage": "English"},
    {"name": "quest/031/BanNam302_03104", "id": 65, "column": 1, "forceLanguage": "English"},
    {"name": "quest/032/FesEst502_03203", "id": 87, "column": 1, "forceLanguage": "English"},
    {"name": "quest/032/FesEst503_03204", "id": 82, "column": 1, "forceLanguage": "English"},
    {"name": "quest/032/LucKbc005_03214", "id": 144, "column": 1, "forceLanguage": "English"},
    {"name": "quest/032/LucKbc012_03221", "id": 140, "column": 1, "forceLanguage": "English"},
    {"name": "quest/032/LucKla302_03234", "id": 63, "column": 1, "forceLanguage": "English"},
    {"name": "quest/033/LucKmb109_03310", "id": 76, "column": 1, "forceLanguage": "English"},
    {"name": "quest/033/LucKmb109_03310", "id": 81, "column": 1, "forceLanguage": "English"},
    {"name": "quest/033/LucKmb109_03310", "id": 84, "column": 1, "forceLanguage": "English"},
    {"name": "quest/033/LucKmc104_03325", "id": 106, "column": 1, "forceLanguage": "English"},
    {"name": "quest/033/LucKza016_03358", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/033/LucKzc012_03395", "id": 56, "column": 1, "forceLanguage": "English"},
    {"name": "quest/033/LucKzc014_03397", "id": 60, "column": 1, "forceLanguage": "English"},
    {"name": "quest/034/LucKzd019_03426", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/034/LucKze007_03441", "id": 55, "column": 1, "forceLanguage": "English"},
    {"name": "quest/034/LucKze007_03441", "id": 62, "column": 1, "forceLanguage": "English"},
    {"name": "quest/034/LucKze010_03444", "id": 55, "column": 1, "forceLanguage": "English"},
    {"name": "quest/035/LucKzi014_03550", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/036/BanPix103_03691", "id": 64, "column": 1, "forceLanguage": "English"},
    {"name": "quest/037/BanPix124_03712", "id": 59, "column": 1, "forceLanguage": "English"},
    {"name": "quest/038/BanQiq114_03819", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/039/BanDwa108_03909", "id": 65, "column": 1, "forceLanguage": "English"},
    {"name": "quest/039/LucKra304_03978", "id": 141, "column": 1, "forceLanguage": "English"},
    {"name": "quest/039/LucKta301_03952", "id": 101, "column": 1, "forceLanguage": "English"},
    {"name": "quest/042/AktKze002_04241", "id": 52, "column": 1, "forceLanguage": "English"},
    {"name": "quest/042/AktKze013_04252", "id": 55, "column": 1, "forceLanguage": "English"},
    {"name": "quest/042/AktKzf007_04262", "id": 54, "column": 1, "forceLanguage": "English"},
    {"name": "quest/043/AktKzi002_04317", "id": 65, "column": 1, "forceLanguage": "English"},
    {"name": "quest/043/AktKzj008_04344", "id": 57, "column": 1, "forceLanguage": "English"},
    {"name": "quest/044/AktKme107_04425", "id": 135, "column": 1, "forceLanguage": "English"},
    {"name": "quest/044/AktKme107_04425", "id": 142, "column": 1, "forceLanguage": "English"}
  ],
  "rules": []
}
